name: Build and deploy Python app

env:
  AZURE_WEBAPP_NAME: pg-oc-test   # Nom de l'application Azure
  PYTHON_VERSION: '3.10'       # Version de Python à utiliser
  WORKING_DIRECTORY: '.'          # Répertoire de travail
  STARTUP_COMMAND: 'uvicorn main:app --reload'  # Commande de démarrage

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
  
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install dependencies
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          python3 -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install setuptools
          pip install -r requirements.txt

#      # Run tests
#      - name: Run tests
#        working-directory: ${{ env.WORKING_DIRECTORY }}
#        run: |
#          source antenv/bin/activate
#          pytest test_main.py

      # Azure login
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}

      # Configure Azure App Service settings
      - uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          mask-inputs: false
          general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}'

      # Deploy web app
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.WORKING_DIRECTORY }}
          startup-command: ${{ env.STARTUP_COMMAND }}

      # Azure logout
      - name: Azure logout
        run: |
          az logout
