name: Build and deploy Python app to Azure Web App - pg-oc-test

env:
  AZURE_WEBAPP_NAME: pg-oc-test   # Nom de votre application sur Azure Web App
  PYTHON_VERSION: '3.10.14'       # Version de Python à utiliser
  NODE_VERSION: '20.x'            # Version de Node.js à utiliser (si nécessaire)
  WORKING_DIRECTORY: '.'          # Répertoire de travail à partir duquel déployer (par défaut, le répertoire racine)
  STARTUP_COMMAND: 'uvicorn main:app --reload'  # Commande de démarrage de votre application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4
        with:
          lfs: true  # Assure le téléchargement des fichiers LFS

      - name: Setup de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup de la version Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Création et activation de l'environnement virtuel
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Mise à jour de pip
        run: |
          python -m pip install --upgrade pip

      - name: Configuration du cache des dépendances
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Installation des dépendances
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip list  # Affiche la liste des paquets installés pour vérification

      - name: Exécution des tests
        run: |
          source venv/bin/activate
          pytest test_main.py

      - name: Upload de l'artefact pour le déploiement
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production  # Vérifiez que cette ligne est correctement écrite sans guillemets supplémentaires
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Téléchargement de l'artefact depuis le job de build
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: Déploiement sur Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
          startup-command: ${{ env.STARTUP_COMMAND }}
