name: Build and deploy Python app

env:
  AZURE_WEBAPP_NAME: pg-oc-test   # Nom de l'application Azure
  PYTHON_VERSION: '3.10'       # Version de Python à utiliser
  WORKING_DIRECTORY: '.'          # Répertoire de travail
  STARTUP_COMMAND: 'uvicorn main:app --reload'  # Commande de démarrage

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
  
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          lfs: true  # Active le support de Git LFS


      - name: Setup de la version Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Création et activation de l'environnement virtuel
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Mise à jour de pip
        run: |
          python -m pip install --upgrade pip

      - name: Configuration du cache des dépendances
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Installation des dépendances
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip list  # Affiche la liste des paquets installés pour vérification

      # Run tests
      - name: Run tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          source venv/bin/activate
          pytest test_main.py

      # Azure login
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}

      # Configure Azure App Service settings
      - uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          mask-inputs: false
          general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}'

      # Deploy web app
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.WORKING_DIRECTORY }}
          startup-command: ${{ env.STARTUP_COMMAND }}

      # Azure logout
      - name: Azure logout
        run: |
          az logout
