name: Build and deploy Python app to Azure Web App - pg-oc-test

env:
  AZURE_WEBAPP_NAME: pg-oc-test   # Nom de votre application sur Azure Web App
  PYTHON_VERSION: '3.10.14'       # Version de Python à utiliser
  NODE_VERSION: '20.x'            # Version de Node.js à utiliser (si nécessaire)
  WORKING_DIRECTORY: '.'          # Répertoire de travail à partir duquel déployer (par défaut, le répertoire racine)
  STARTUP_COMMAND: 'uvicorn main:app --reload'  # Commande de démarrage de votre application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v2
        with:
          lfs: true  # Assure le téléchargement des fichiers LFS

      - name: Setup de la version Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Création et activation de l'environnement virtuel
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Mise à jour de pip
        run: |
          python -m pip install --upgrade pip

      - name: Installation des dépendances
        run: |
          pip install -r requirements.txt
          pip list  # Affiche la liste des paquets installés pour vérification

      - name: Exécution des tests
        run: |
          source venv/bin/activate
          pytest test_main.py

#      - name: Upload artifact for deployment jobs
#        uses: actions/upload-artifact@v2
#        with:
#          name: python-app
#          path: |
#            . 
#            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
#      - name: Download artifact from build job
#        uses: actions/download-artifact@v2
#        with:
#          name: python-app
#          path: .
          
      - name: Déploiement sur Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          startup-command: ${{ env.STARTUP_COMMAND }}